apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minikube-ingress
  annotations:
spec:
  rules:
  - host: api.aistream
    http:
      paths:
      - path: /
        backend:
          serviceName: flask
          servicePort: 5000